services:
  - type: web
    name: atlas-signature-gateway
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    envVars:
      - fromDotEnv: true
