# render.yaml
# Deployment configuration for Atlas Signature Gateway (EyesUnclouded Universe)
# This file tells Render how to build and run your Flask-based symbolic gateway.

services:
  - type: web
    name: atlas-signature-gateway
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    envVars:
      - fromDotEnv: true

